---
- name: Include Debian specific variables
  include_vars:
    file: "{{ item }}"
  with_items:
    - "Debian-{{ ansible_distribution_major_version }}.yml"
    - "Debian.yml"


- name: "Install Docker requirements for Debian {{ ansible_distribution_major_version }}"
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items: "{{ docker_common_packages }} + {{ docker_extra_packages }}"

- name: "Add Docker GPG key"
  apt_key:
   url: "{{ docker_gpg_url }}"
   state: present

- name: "Add Docker Repository"
  apt_repository:
   repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
   state: present
   filename: "docker"

- name: "Install Docker"
  apt:
   name: "{{ docker_package_type }}"
   state: present
   update_cache: yes
