---
- name: "Install Docker requirements for debian 8 and after"
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - python-software-properties
  when: ansible_distribution_major_version|int >= 8


- name: "Install Docker requirements for Debian 7 and before"
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - python-software-common
  when: ansible_distribution_major_version|int <= 7

- name: "Add Docker GPG key"
  apt_key:
   url: "{{ docker_gpg_url }}"
   state: present

- name: "Add Docker Repository"
  apt_repository:
   repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
   state: present
   filename: "docker"

- name: "Install Docker"
  apt:
   name: "{{ docker_package_type }}"
   state: present
   update_cache: yes
