---
- name: "Include {{ ansible_distribution }} specific tasks"
  include: "{{ansible_distribution }}.yml"

- name: "Ensure docker service is started"
  service:
   name: docker
   state: started
   enabled: yes

- include: config.yml

- name: "Include docker-machine.yml"
  include: docker-machine.yml
  when: docker_machine == True

- name: "Include docker-compose.yml"
  include: docker-compose.yml
  when: docker_compose == True
