---
- name: "Include Ubuntu specific variables"
  include_vars:
    file: "{{ item }}"
  with_items:
  - "Ubuntu.yml"

- name: "Install Docker requirements "
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
     #  with_items: "{{ docker_common_packages }} + {{ docker_extra_packages }}"
  loop: "{{ docker_common_packages +docker_extra_packages}}"

- name: "Add Docker GPG key"
  apt_key:
   url: "{{ docker_gpg_url }}"
   state: present
   keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: "Add Docker Repository"
  apt_repository:
   repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
   state: present
   filename: "docker"

- name: "Install Docker"
  apt:
   name: "{{ docker_packages }}"
   state: present
   update_cache: yes
